# Reference: https://docs.readthedocs.io/en/latest/yaml-config.html

build:
  image: stable
  os: ubuntu-22.04

# Possible options: htmlzip, pdf, epub
# Disable (single) htmlzip as it's way too big to be useful,
# and leads to excessive memory usage on build
# Disable epub and pdf for now to speed up builds
# formats:
#   - pdf
